### ISSUE TITLE
[Bug] Springboard icons disappear 

### ISSUE THREAD

**Issue by inkrypted** [nathanwhit/Springfinity#2]
When coming out of landscape mode to vertical screen, the last 2-3 rows of icons just disappear.

**Comment by nathanwhit** [comment]
What version of the tweak are you using? What device do you have? iOS version? Tweaks installed?
I need a bit more info

**Comment by inkrypted** [comment]
Sorry im on a 7+ 12.1.2, unc0ver 3.0.1, issue was on Springfinity version 1.1.7. Ive updated since and will see if i can reproduce the issue. To fix the issue i had to disable rotation. I’ll update you again soon. Thanks for this awesome tweak.

**Comment by inkrypted** [comment]
Can i have an update on this issue? It is very annoying!

![85F7D443-0806-43A9-98A0-19F4E9189164](https://user-images.githubusercontent.com/7110560/58769507-ca1bd400-8575-11e9-9f37-edd4a8916282.png)

**Comment by nathanwhit** [comment]
Sorry about the delay, this should be fixed in a new update (version 1.1.9).
You can get it now on my beta repo : [https://nathanwhit.github.io/repo](https://nathanwhit.github.io/repo) . Test it out and let me know how it goes. If all goes well I'll submit the update to BigBoss.

**Comment by inkrypted** [comment]
Just installed it I will let you know how it goes. So far so good though.

**Comment by inkrypted** [comment]
Issue is fixed with latest beta. Thank you
